## Regressão logística ####
modelo.desfecho.atb <- glm(Desfecho ~ ATB, family = binomial(link = "logit"))
modelo.desfecho.diab <- glm(Desfecho ~ DM, family = binomial(link = "logit"))
modelo.desfecho.sexo <- glm(Desfecho ~ Sexo, family = binomial(link = "logit"))
modelo.desfecho.idade <- glm(Desfecho ~ Idade, family = binomial(link = "logit"))
modelo.desfecho.imc <- glm(Desfecho ~ IMC, family = binomial(link = "logit"))
modelo.desfecho.ptn <- glm(Desfecho ~ ptn, family = binomial(link = "logit"))
modelo.desfecho.diag <- glm(Desfecho ~ Diagnóstico, family = binomial(link = "logit"))
summary(modelo.desfecho.atb)
summary(modelo.desfecho.diab)
summary(modelo.desfecho.sexo)
summary(modelo.desfecho.idade)
summary(modelo.desfecho.imc)
summary(modelo.desfecho.ptn)
summary(modelo.desfecho.diag)

modelo.desfecho.full <- glm(Desfecho ~ ATB + DM + Sexo + Idade + IMC + ptn + Diagnóstico, family = binomial(link = "logit"))
summary(modelo.desfecho.full)
